package com.bbd.BeanServer.db_classes;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import lombok.Data;

@Entity
@Data
public class Users {
  
  @Id @GeneratedValue
  Long user_id;
  int user_role_id;
  int favorite_bean_id;
  String username;
  String bio;

  Users() {

  }

  Users(Long userRole, int favoriteBean, String username, String bio) {
    this.user_id = userRole;
    this.favorite_bean_id= favoriteBean;
    this.username = username;
    this.bio = bio;
  }
}

// CREATE TABLE "User" (
//   "UserID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
//   "UserRoleID" int NOT NULL,
//   "FavoriteBeanID" int NOT NULL,
//   "Username" varchar(50) NOT NULL,
//   "Bio" varchar(500) NOT NULL
// );

