-- CREATE SCRIPTS

CREATE TABLE users (
  user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  user_role_id int NOT NULL,
  favorite_bean_id int NOT NULL,
  username varchar(50) NOT NULL,
  bio varchar(500) NOT NULL
);

CREATE TABLE favorite_bean (
  favorite_bean_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  bean_name varchar(50) NOT NULL,
  is_banned boolean NOT NULL
);

CREATE TABLE user_role (
  user_role_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  role_name varchar(50) NOT NULL
);

CREATE TABLE post (
  post_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  user_id int NOT NULL,
  tag_id int NOT NULL,
  post_title varchar(50) NOT NULL,
  post_content varchar(500) NOT NULL,
  date_posted timestamp
);

CREATE TABLE tag (
  tag_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  tag_name varchar(50) NOT NULL
);

CREATE TABLE comment (
  comment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  post_id int NOT NULL,
  user_id int NOT NULL,
  comment_info varchar(100) NOT NULL,
  date_posted timestamp

);

CREATE TABLE reaction (
  reaction_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  user_id int NOT NULL,
  reaction_type_id int NOT NULL,
  date_of_reaction timestamp NOT NULL
);

CREATE TABLE reaction_type (
  reaction_type_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  bean_name varchar(50) NOT NULL
);

CREATE TABLE post_reaction (
  post_reaction_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  post_id int NOT NULL,
  reaction_id int NOT NULL
);

CREATE TABLE comment_reaction (
  comment_reaction_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  comment_id int NOT NULL,
  reaction_id int NOT NULL
);

ALTER TABLE users ADD FOREIGN KEY (user_role_id) REFERENCES user_role (user_role_id);

ALTER TABLE users ADD FOREIGN KEY (favorite_bean_id) REFERENCES favorite_bean (favorite_bean_id);

ALTER TABLE post ADD FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE post ADD FOREIGN KEY (tag_id) REFERENCES tag (tag_id);

ALTER TABLE post_reaction ADD FOREIGN KEY (post_id) REFERENCES post (post_id);

ALTER TABLE post_reaction ADD FOREIGN KEY (reaction_id) REFERENCES reaction (reaction_id);

ALTER TABLE comment_reaction ADD FOREIGN KEY (reaction_id) REFERENCES reaction (reaction_id);

ALTER TABLE reaction ADD FOREIGN KEY (reaction_type_id) REFERENCES reaction_type (reaction_type_id);

ALTER TABLE comment_reaction ADD FOREIGN KEY (comment_id) REFERENCES comment (comment_id);


