INSERT INTO favouriteBean (Name, isBanned)
VALUES
('Acacia holosericea', false),
('Adzuki bean', false),
('Alb-Leisa', false),
('Apios americana', false),
('Appaloosa bean', false),
('Arachis hypogaea', false),
('Archidendron pauciflorum', false),
('Asparagus bean', false),
('Bean', false),
('Black adzuki bean', false),
('Black turtle bean', false),
('Black-eyed pea', false),
('Bolita bean', false),
('Broad bean', false),
('Cajanus cajan', false),
('Cajanus scarabaeoides', false),
('Calypso bean', false),
('Canavalia gladiata', false),
('Caragana arborescens', false),
('Carob', false),
('Catjang', false),
('Chickpea', false),
('Cicer', false),
('Cicer arietinum', false),
('Cowpea', false),
('Crotalaria longirostrata', false),
('Detarium microcarpum', false),
('Detarium senegalense', false),
('Dixie Lee pea', false),
('Dragon tongue bean', false),
('Erythrina edulis', false),
('Fabes de la Granja', false),
('Fava bean', false),
('Fenugreek', false),
('Flageolet bean', false),
('Flat bean', false),
('Genetically modified soybean', false),
('Glycine max', false),
('Green bean', false),
('Guar', false),
('Honey locust', false),
('Inga edulis', false),
('Inga feuilleei', false),
('Inocarpus fagifer', false),
('Kidney bean', false),
('Lablab', false),
('Lablab purpureus', false),
('Lathyrus aphaca', false),
('Lathyrus japonicus', false),
('Lathyrus sativus', false),
('Le Puy green lentil', false),
('Lentil', false),
('Lima bean', false),
('Lupin bean', false),
('Lupinus luteus', false),
('Macrotyloma geocarpum', false),
('Macrotyloma uniflorum', false),
('Mesquite', false),
('Mucuna pruriens', false),
('Mung bean', false),
('Neptunia oleracea', false),
('Parkia javanica', false),
('Parkia speciosa', false),
('Parkia timoriana', false),
('Parkinsonia florida', false),
('Parkinsonia microphylla', false),
('Peanut', false),
('Pediomelum cuspidatum', false),
('Pediomelum esculentum', false),
('Phaseolus acutifolius', false),
('Phaseolus coccineus', false),
('Phaseolus vulgaris', false),
('Pigeon pea', false),
('Pinquito bean', false),
('Pinto bean', false),
('Pithecellobium dulce', false),
('Pochas', false),
('Prosopis alba', false),
('Prosopis glandulosa', false),
('Prosopis nigra', false),
('Prosopis pubescens', false),
('Prosopis velutina', false),
('Sea Island red pea', false),
('Senna tora', false),
('Shucky beans', false),
('Snap pea', false),
('Snow pea', false),
('Sorana bean', false),
('Soybean', false),
('Split pea', false),
('Tamarind', false),
('Tarbais bean', false),
('Trigonella caerulea', false),
('Tylosema esculentum', false),
('Vicia faba', false),
('Vicia lens', false),
('Vigna aconitifolia', false),
('Vigna mungo', false),
('Vigna subterranea', false),
('Vigna umbellata', false),
('Wattleseed', false),
('Winged bean', false);
--
--INSERT INTO favouriteBean (favouriteBeanID, Name, isBanned)
--VALUES
--(1, 'Acacia holosericea', false),
--(2, 'Adzuki bean', false),
--(3, 'Alb-Leisa', false),
--(4, 'Apios americana', false),
--(5, 'Appaloosa bean', false),
--(6, 'Arachis hypogaea', false),
--(7, 'Archidendron pauciflorum', false),
--(8, 'Asparagus bean', false),
--(9, 'Bean', false),
--(10, 'Black adzuki bean', false),
--(11, 'Black turtle bean', false),
--(12, 'Black-eyed pea', false),
--(13, 'Bolita bean', false),
--(14, 'Broad bean', false),
--(15, 'Cajanus cajan', false),
--(16, 'Cajanus scarabaeoides', false),
--(17, 'Calypso bean', false),
--(18, 'Canavalia gladiata', false),
--(19, 'Caragana arborescens', false),
--(20, 'Carob', false),
--(21, 'Catjang', false),
--(22, 'Chickpea', false),
--(23, 'Cicer', false),
--(24, 'Cicer arietinum', false),
--(25, 'Cowpea', false),
--(26, 'Crotalaria longirostrata', false),
--(27, 'Detarium microcarpum', false),
--(28, 'Detarium senegalense', false),
--(29, 'Dixie Lee pea', false),
--(30, 'Dragon tongue bean', false),
--(31, 'Erythrina edulis', false),
--(32, 'Fabes de la Granja', false),
--(33, 'Fava bean', false),
--(34, 'Fenugreek', false),
--(35, 'Flageolet bean', false),
--(36, 'Flat bean', false),
--(37, 'Genetically modified soybean', false),
--(38, 'Glycine max', false),
--(39, 'Green bean', false),
--(40, 'Guar', false),
--(41, 'Honey locust', false),
--(42, 'Inga edulis', false),
--(43, 'Inga feuilleei', false),
--(44, 'Inocarpus fagifer', false),
--(45, 'Kidney bean', false),
--(46, 'Lablab', false),
--(47, 'Lablab purpureus', false),
--(48, 'Lathyrus aphaca', false),
--(49, 'Lathyrus japonicus', false),
--(50, 'Lathyrus sativus', false),
--(51, 'Le Puy green lentil', false),
--(52, 'Lentil', false),
--(53, 'Lima bean', false),
--(54, 'Lupin bean', false),
--(55, 'Lupinus luteus', false),
--(56, 'Macrotyloma geocarpum', false),
--(57, 'Macrotyloma uniflorum', false),
--(58, 'Mesquite', false),
--(59, 'Mucuna pruriens', false),
--(60, 'Mung bean', false),
--(61, 'Neptunia oleracea', false),
--(62, 'Parkia javanica', false),
--(63, 'Parkia speciosa', false),
--(64, 'Parkia timoriana', false),
--(65, 'Parkinsonia florida', false),
--(66, 'Parkinsonia microphylla', false),
--(67, 'Peanut', false),
--(68, 'Pediomelum cuspidatum', false),
--(69, 'Pediomelum esculentum', false),
--(70, 'Phaseolus acutifolius', false),
--(71, 'Phaseolus coccineus', false),
--(72, 'Phaseolus vulgaris', false),
--(73, 'Pigeon pea', false),
--(74, 'Pinquito bean', false),
--(75, 'Pinto bean', false),
--(76, 'Pithecellobium dulce', false),
--(77, 'Pochas', false),
--(78, 'Prosopis alba', false),
--(79, 'Prosopis glandulosa', false),
--(80, 'Prosopis nigra', false),
--(81, 'Prosopis pubescens', false),
--(82, 'Prosopis velutina', false),
--(83, 'Sea Island red pea', false),
--(84, 'Senna tora', false),
--(85, 'Shucky beans', false),
--(86, 'Snap pea', false),
--(87, 'Snow pea', false),
--(88, 'Sorana bean', false),
--(89, 'Soybean', false),
--(90, 'Split pea', false),
--(91, 'Tamarind', false),
--(92, 'Tarbais bean', false),
--(93, 'Trigonella caerulea', false),
--(94, 'Tylosema esculentum', false),
--(95, 'Vicia faba', false),
--(96, 'Vicia lens', false),
--(97, 'Vigna aconitifolia', false),
--(98, 'Vigna mungo', false),
--(99, 'Vigna subterranea', false),
--(100, 'Vigna umbellata', false),
--(101, 'Wattleseed', false),
--(102, 'Winged bean', false);
