name: Maven Test

on:
  push:
    branches:
      - derryk/feature/unittests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('Server/pom.xml') }} # Change the path to server/pom.xml
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Maven test
        working-directory: /Server/BeanServer # Change the working directory to server
        run: mvn test
